#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf VTK
rm -rf constant/cellToRegion constant/polyMesh/sets
rm -rf 0/air
rm -rf 0/heater
rm -rf 0/surrondingSolid
rm -f 0/cellToRegion
rm -rf constant/air/polyMesh
rm -rf constant/heater/polyMesh
rm -rf constant/surronding/polyMesh
rm -rf logs

# ----------------------------------------------------------------- end-of-file
