#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`


blockMesh
snappyHexMesh -overwrite
createPatch -overwrite
transformPoints 'scale=(0.05 0.05 0.05)'
cp 0/U.org 0/U
cp 0/p.org 0/p
renumberMesh -overwrite
potentialFoam -writep -writePhi
runApplication $application

# ----------------------------------------------------------------- end-of-file
