#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions



blockMesh
cp 0/T.org 0/T
setFields
reactingFoam > log.reactingFoam
# decomposePar
# mpirun -np 8 reactingFoam -parallel > log.reactingFoam
# reconstructPar


