#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions


cd ./
cleanCase 
rm -rf 0/alpha1 && rm -rf l* swak*

# ----------------------------------------------------------------- end-of-file
