#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cd coarse
cleanCase
rm -rf constant/polyMesh
rm *.msh

cd ../fine
cleanCase
rm -rf 0 constant/polyMesh
rm *.msh

cd ../
rm -rf Mesh*

clear


# ----------------------------------------------------------------- end-of-file
