#!/bin/sh
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     |
#   \\  /    A nd           | Copyright (C) 2011 OpenFOAM Foundation
#    \\/     M anipulation  |
#-------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# Script
#     createGraphs
#
# Description
#     Creates .eps graphs of OpenFOAM results vs experiment for the buoyant
#     cavity case
#
#------------------------------------------------------------------------------

createEpsT()
{
    p1=$1
    p2=$2
    pExp=$3 

    gnuplot<<EOF
    set terminal postscript eps color enhanced
    set output "OF.eps"
    set xlabel "Time,[s]"
    #set ylabel "Cd"
    #set grid
    set key right top
    set size 0.6, 0.6
    set xrange [0:40]
    set yrange [-10:20]
    plot \
        "$p1" u  1:2 title "Cd"  with lines linetype 5 lc rgb "red", \
        "$p2" u  1:3 title "Cl"  with lines linetype 5 lc rgb "green"          
EOF
}


# test if gnuplot exists on the system
type -P gnuplot &>/dev/null || {
    echo "gnuplot not found - skipping graph creation" >&2
    exit 1
}


# paths to data
file1=./forceCoeffs/0/forceCoeffs.dat


p1="$file1"



# generate temperature profiles
createEpsT $p1 


#------------------------------------------------------------------------------
