#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# creat mesh
blockMesh 

#solve problem
icoFoam > log & 
sleep 3 
foamMonitor -l postProcessing/residuals\(p\)/0/residuals.dat

paraFoam -touchAll

# ----------------------------------------------------------------- end-of-file
