#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

clear

#copy and place the mesh file in directories
echo copy files ...
wget http://nimasamkhaniani.ir/wp-content/uploads/2021/04/Mesh.tar.gz
tar -xzf Mesh.tar.gz
cp Mesh/buildingComplexCoarse.msh coarse
cp Mesh/buildingComplexFine.msh  fine


#run the simulation in coarse grid
cd coarse
runApplication fluent3DMeshToFoam buildingComplexCoarse.msh
runApplication decomposePar
mpirun -np 4 simpleFoam -parallel > log.simpleFoam 
runApplication reconstructPar -latestTime

#run the simulation in fine grid
cd ../fine
cp -a 0.org 0
runApplication fluent3DMeshToFoam buildingComplexFine.msh
runApplication mapFields -consistent -sourceTime latestTime ../coarse/
runApplication decomposePar
mpirun -np 4 simpleFoam -parallel > log.simpleFoam
runApplication reconstructPar -latestTime
#runApplication foamCalc mag U -latestTime   #oldVersion of OpenFOAM (OF< 3 or 4)
#runApplication sample -latestTime
postProcess -func "mag(U)" -latestTime
postProcess -func sample -latestTime
