#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions



blockMesh
#XiFoam > log.XiFoam
decomposePar
mpirun -np 4 XiFoam -parallel > log.XiFoam
reconstructPar
postProcess -func vorticity
XiFoam -postProcess -func yPlus
